### ISSUE TITLE
Errror in authenticatie

### ISSUE THREAD

**Issue by arnegoeteyn** [FOSDeKangoeroes/kangoeroes.leidingbeheer.frontend#2]
Het starten van de app op de huidige master zorgt voor een error ergens. Kzal vanavond eens proberen kijken of ik hem vind.
Deze fout is er nog niet in commit abb364f en wordt dus geintroduceert in 638005f

Ik vermoed dat het iets met authenticatie te maken heeft aangezien alle commits daarna rond authenticatie zijn :p

`Stack trace: resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:824:31 resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:795:17 scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:873:17 ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:425:17 onInvokeTask@webpack-internal:///../../../core/esm5/core.js:4815:24 ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17 Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28 drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:602:25`

**Comment by thomasdewulf** [comment]
Je mist een environment file die niet wordt mee gecommit omdat daar geheime waarden instaan om te connecteren met de auth server

**Comment by arnegoeteyn** [comment]
Krijg ik die environment file?

**Comment by thomasdewulf** [comment]
Al gefixt ondertussen?

**Comment by arnegoeteyn** [comment]
Nog niet getest, druk druk druj
